---
title: 使用ansible过程中的疑问
date: 2022-10-25 22:18:33
permalink: /pages/d6198d/
categories:
  - 运维
  - ansible
tags:
  - 
---
# 使用ansible过程中的疑问

## 1.遇到报错，我想要抛出报错之后继续执行

```yml
---
- hosts: test1
  remote_user: root
  tasks:
  - name: "报错捕获测试"
    command: "setenforce 0 "
    register: command_result
    ignore_errors: True
  - name: "打印出相关报错"
    debug: 
      msg: "{{ command_result }}"
```

## 2.使用set_fact设置的变量可以给多个使用